# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a7a9994e7832d4cd62867756782671e4a19737c48d653a8e9c398122e24fba151cbd5e78beb32df5ab703776c50e3c75009d464ef282d07cfb875c28e239e3

test:
  secret_key_base: 8038404a4252163ada14152863741665b47c731c79f2323bdc993530ebbc95eb672bfa506f3607fe0c36331e4cab6aaa7cf5d4601652f07f035ede520d6c963c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
